"""versionado de sabanas

Revision ID: 1fe354a9a285
Revises:
Create Date: 2026-09-11 15:16:23.666785

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1fe354a9a285"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carga",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("fecha_corte", sa.Date(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("vigente", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("estado", sa.String(length=20), server_default="en_cola", nullable=False),
        sa.Column("nombre_archivo", sa.Text(), nullable=False),
        sa.Column("huella_archivo", sa.String(length=64), nullable=False),
        sa.Column("tamano_bytes", sa.BigInteger(), nullable=False),
        sa.Column("hoja", sa.Text(), server_default="VENCIDA", nullable=False),
        sa.Column("huella_formato", sa.String(length=64), nullable=True),
        sa.Column("fila_cabecera", sa.Integer(), nullable=True),
        sa.Column("cabeceras_originales", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mapeo", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("filas_total", sa.Integer(), nullable=True),
        sa.Column("filas_ingestadas", sa.Integer(), nullable=True),
        sa.Column("incidencias_error", sa.Integer(), server_default="0", nullable=False),
        sa.Column("incidencias_advertencia", sa.Integer(), server_default="0", nullable=False),
        sa.Column("incidencias_info", sa.Integer(), server_default="0", nullable=False),
        sa.Column("motivo_fallo", sa.Text(), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("procesado_en", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT vigente OR estado = 'terminada'", name=op.f("ck_carga_vigente_terminada")
        ),
        sa.CheckConstraint(
            "estado IN ('en_cola', 'procesando', 'terminada', 'fallida')",
            name=op.f("ck_carga_estado_valido"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_carga_version_positiva")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carga")),
        sa.UniqueConstraint("fecha_corte", "version", name=op.f("uq_carga_fecha_corte_version")),
    )
    op.create_index(
        op.f("ix_carga_fecha_corte_huella_archivo"),
        "carga",
        ["fecha_corte", "huella_archivo"],
        unique=False,
    )
    op.create_index(
        "uq_carga_vigente_por_fecha",
        "carga",
        ["fecha_corte"],
        unique=True,
        postgresql_where="vigente",
    )
    op.create_table(
        "carga_auditoria",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("carga_id", sa.BigInteger(), nullable=False),
        sa.Column("fecha_corte", sa.Date(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("evento", sa.String(length=30), nullable=False),
        sa.Column("nombre_archivo", sa.Text(), nullable=True),
        sa.Column("huella_archivo", sa.String(length=64), nullable=True),
        sa.Column("filas_total", sa.Integer(), nullable=True),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ocurrido_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evento IN ('carga_creada', 'procesamiento_terminado', 'procesamiento_fallido', "
            "'vigente_asignada', 'vigente_retirada', 'carga_eliminada')",
            name=op.f("ck_carga_auditoria_evento_valido"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carga_auditoria")),
    )
    op.create_index(
        op.f("ix_carga_auditoria_fecha_corte_ocurrido_en"),
        "carga_auditoria",
        ["fecha_corte", "ocurrido_en"],
        unique=False,
    )
    op.create_table(
        "carga_archivo",
        sa.Column("carga_id", sa.BigInteger(), nullable=False),
        sa.Column("contenido", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carga_id"],
            ["carga.id"],
            name=op.f("fk_carga_archivo_carga_id_carga"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("carga_id", name=op.f("pk_carga_archivo")),
    )
    # Ajuste manual: el .xlsb ya viene comprimido (zip); EXTERNAL evita que PostgreSQL
    # gaste CPU intentando comprimirlo de nuevo. Autogenerate no detecta este atributo.
    op.execute("ALTER TABLE carga_archivo ALTER COLUMN contenido SET STORAGE EXTERNAL")
    op.create_table(
        "carga_fila",
        sa.Column("carga_id", sa.BigInteger(), nullable=False),
        sa.Column("pagare", sa.Text(), nullable=False),
        sa.Column("numero_fila", sa.Integer(), nullable=False),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("agencia", sa.Text(), nullable=True),
        sa.Column("analista_asignacion", sa.Text(), nullable=True),
        sa.Column("titular", sa.Text(), nullable=True),
        sa.Column("documento_tipo", sa.String(length=12), nullable=True),
        sa.Column("documento_numero", sa.Text(), nullable=True),
        sa.Column("telefono", sa.String(length=9), nullable=True),
        sa.Column("saldo_soles_corte", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("tipo_reprogramacion", sa.Text(), nullable=True),
        sa.Column("vencimiento_operativo_aplica", sa.Boolean(), nullable=True),
        sa.Column("vencimiento_operativo_fecha", sa.Date(), nullable=True),
        sa.Column("dias_atraso", sa.Integer(), nullable=True),
        sa.Column("analista_actual", sa.Text(), nullable=True),
        sa.Column("saldo_capital_pendiente", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("monto_cuota", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("estado_credito", sa.Text(), nullable=True),
        sa.Column("fecha_vencimiento_cuota", sa.Date(), nullable=True),
        sa.Column("cliente_fallecido", sa.Boolean(), nullable=True),
        sa.Column("dias_atraso_entidad", sa.Integer(), nullable=True),
        sa.Column("cuotas_aprobadas", sa.Integer(), nullable=True),
        sa.Column("cuotas_pagadas", sa.Integer(), nullable=True),
        sa.Column("cuotas_pendientes", sa.Integer(), nullable=True),
        sa.Column("tipo_basilea", sa.Text(), nullable=True),
        sa.Column("tipo_producto", sa.Text(), nullable=True),
        sa.Column("segmento_saldo", sa.Text(), nullable=True),
        sa.Column("moneda", sa.Text(), nullable=True),
        sa.Column("valor_cierre_mes_anterior", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("saldo_cierre_actual", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("bpo", sa.Text(), nullable=True),
        sa.Column("cartera_tag", sa.Text(), nullable=True),
        sa.Column("mes_gestion", sa.Text(), nullable=True),
        sa.Column("segmento_actual", sa.Text(), nullable=True),
        sa.Column("segmento_financiero", sa.Text(), nullable=True),
        sa.Column("descuento_planilla", sa.Boolean(), nullable=True),
        sa.Column("segmento_atraso", sa.Text(), nullable=True),
        sa.Column("tramo_actual", sa.Text(), nullable=True),
        sa.Column("provision_actual", sa.Text(), nullable=True),
        sa.Column("mora_impacto_actual", sa.Boolean(), nullable=True),
        sa.Column("tramo_proyectado", sa.Text(), nullable=True),
        sa.Column("provision_proyectada", sa.Text(), nullable=True),
        sa.Column("mora_impacto_proyectada", sa.Boolean(), nullable=True),
        sa.Column("cantidad_paralelos", sa.Integer(), nullable=True),
        sa.Column("celular_analista", sa.String(length=9), nullable=True),
        sa.Column("extras", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "documento_tipo IS NULL OR documento_tipo IN ('dni', 'ruc', 'extranjero')",
            name=op.f("ck_carga_fila_documento_tipo_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["carga_id"],
            ["carga.id"],
            name=op.f("fk_carga_fila_carga_id_carga"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("carga_id", "pagare", name=op.f("pk_carga_fila")),
    )
    op.create_index(
        op.f("ix_carga_fila_pagare_carga_id"), "carga_fila", ["pagare", "carga_id"], unique=False
    )
    op.create_table(
        "carga_incidencia",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("carga_id", sa.BigInteger(), nullable=False),
        sa.Column("fila", sa.Integer(), nullable=True),
        sa.Column("columna", sa.Text(), nullable=True),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("severidad", sa.String(length=12), nullable=False),
        sa.Column("detalle", sa.Text(), nullable=False),
        sa.Column("valor_original", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "severidad IN ('error', 'advertencia', 'info')",
            name=op.f("ck_carga_incidencia_severidad_valida"),
        ),
        sa.ForeignKeyConstraint(
            ["carga_id"],
            ["carga.id"],
            name=op.f("fk_carga_incidencia_carga_id_carga"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carga_incidencia")),
    )
    op.create_index(
        op.f("ix_carga_incidencia_carga_id_severidad_codigo"),
        "carga_incidencia",
        ["carga_id", "severidad", "codigo"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_carga_incidencia_carga_id_severidad_codigo"), table_name="carga_incidencia"
    )
    op.drop_table("carga_incidencia")
    op.drop_index(op.f("ix_carga_fila_pagare_carga_id"), table_name="carga_fila")
    op.drop_table("carga_fila")
    op.drop_table("carga_archivo")
    op.drop_index(op.f("ix_carga_auditoria_fecha_corte_ocurrido_en"), table_name="carga_auditoria")
    op.drop_table("carga_auditoria")
    op.drop_index("uq_carga_vigente_por_fecha", table_name="carga", postgresql_where="vigente")
    op.drop_index(op.f("ix_carga_fecha_corte_huella_archivo"), table_name="carga")
    op.drop_table("carga")
    # ### end Alembic commands ###
