/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Reporta si la API y la base de datos estan disponibles.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cargas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Versiones */
        get: operations["listar_versiones_cargas_get"];
        put?: never;
        /**
         * Subir Sabana
         * @description Registra una version nueva y lanza su procesamiento en segundo plano (V-1).
         */
        post: operations["subir_sabana_cargas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cargas/{carga_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Version */
        get: operations["obtener_version_cargas__carga_id__get"];
        put?: never;
        post?: never;
        /** Eliminar Version */
        delete: operations["eliminar_version_cargas__carga_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cargas/{carga_id}/incidencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Incidencias */
        get: operations["listar_incidencias_cargas__carga_id__incidencias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cargas/{carga_id}/vigente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asignar Vigente
         * @description Regla V-7: elige que version se considera para su fecha.
         */
        post: operations["asignar_vigente_cargas__carga_id__vigente_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartera/campos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Campos
         * @description Campos consultables con su tipo y los operadores que admite cada uno.
         */
        get: operations["listar_campos_cartera_campos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar Cartera
         * @description Productos de la version vigente de la fecha (RF-04, RF-05, RF-08).
         */
        get: operations["consultar_cartera_cartera_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartera/metricas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metricas Cartera
         * @description Capital, cuentas, segmentos y cuotas de la seleccion (RF-26), mas RF-27.
         */
        get: operations["metricas_cartera_cartera_metricas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartera/segmentacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Segmentar Cartera
         * @description Cuentas y capital por cada valor de un atributo (RF-06).
         */
        get: operations["segmentar_cartera_cartera_segmentacion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartera/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumir Cartera
         * @description Metricas del universo filtrado y de sus primeros n, lado a lado (RF-08, RF-26 a RF-28).
         *
         *     Los primeros n son los mismos productos que devuelve `/cartera` con ese orden
         *     y los mismos que se escriben en el archivo de carga.
         */
        get: operations["resumir_cartera_cartera_resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archivos-carga/formatos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Formatos
         * @description Formatos que se pueden generar y que opciones admite cada uno (RF-13).
         */
        get: operations["listar_formatos_archivos_carga_formatos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archivos-carga/previsualizacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Previsualizar
         * @description Primeras filas y errores de la carga, sin escribir el archivo.
         *
         *     `disponibles` es el total de la seleccion completa, no el de la muestra: es
         *     lo que dice si alcanzan los productos para la cantidad pedida (RF-08).
         */
        post: operations["previsualizar_archivos_carga_previsualizacion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archivos-carga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generar Archivo
         * @description Genera la carga completa y devuelve el archivo (RF-09, RF-13, RF-15).
         *
         *     El resumen viaja en cabeceras `X-Carga-*` porque el cuerpo es el archivo;
         *     el detalle de los errores se consulta en `/previsualizacion`.
         */
        post: operations["generar_archivo_archivos_carga_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/selecciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Selecciones
         * @description Todas las selecciones, ordenadas por nombre y revisadas contra el catalogo actual.
         */
        get: operations["listar_selecciones_selecciones_get"];
        put?: never;
        /**
         * Crear Seleccion
         * @description Guarda una seleccion nueva. Si alguna parte no aplica, se rechaza con el motivo.
         */
        post: operations["crear_seleccion_selecciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/selecciones/revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revisar Seleccion
         * @description Que partes no aplican, sin guardar nada: para marcar errores mientras se edita.
         */
        post: operations["revisar_seleccion_selecciones_revision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/selecciones/{seleccion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Seleccion
         * @description Una seleccion. Si perdio validez se devuelve igual, con sus problemas marcados.
         */
        get: operations["obtener_seleccion_selecciones__seleccion_id__get"];
        /**
         * Actualizar Seleccion
         * @description Reemplaza la seleccion completa.
         */
        put: operations["actualizar_seleccion_selecciones__seleccion_id__put"];
        post?: never;
        /** Eliminar Seleccion */
        delete: operations["eliminar_seleccion_selecciones__seleccion_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BloqueRespuesta */
        BloqueRespuesta: {
            metricas: components["schemas"]["MetricasRespuesta"];
            segmentacion: components["schemas"]["SegmentacionRespuesta"] | null;
        };
        /** Body_subir_sabana_cargas_post */
        Body_subir_sabana_cargas_post: {
            /**
             * Fecha Corte
             * Format: date
             * @description Fecha del corte que representa la sabana
             */
            fecha_corte: string;
            /**
             * Archivo
             * @description Archivo de la sabana (.xlsb, .xlsx)
             */
            archivo: string;
            /**
             * Hoja
             * @default VENCIDA
             */
            hoja: string;
        };
        /** CampoEntrada */
        CampoEntrada: {
            /** Nombre */
            nombre: string;
            /** Plantilla */
            plantilla: string;
            /** @default texto */
            tipo: components["schemas"]["TipoSalida"];
            /** Formato Fecha */
            formato_fecha?: string | null;
            formato_financiero?: components["schemas"]["FormatoFinancieroEntrada"] | null;
        };
        /** CampoRespuesta */
        CampoRespuesta: {
            /** Tipo */
            tipo: string;
            /** Operadores */
            operadores: string[];
        };
        /** CargaCreadaRespuesta */
        CargaCreadaRespuesta: {
            /** Id */
            id: number;
            /**
             * Fecha Corte
             * Format: date
             */
            fecha_corte: string;
            /** Version */
            version: number;
            estado: components["schemas"]["EstadoCarga"];
            /** Versiones Identicas */
            versiones_identicas: number[];
            /** Aviso */
            aviso: string | null;
        };
        /** DefinicionEntrada */
        DefinicionEntrada: {
            /** Nombre */
            nombre: string;
            /** Campos */
            campos: components["schemas"]["CampoEntrada"][];
        };
        /**
         * DetalleError
         * @description Motivo legible por el que la API rechazo la peticion.
         */
        DetalleError: {
            /** Detail */
            detail: string;
        };
        /** ErrorGeneracionRespuesta */
        ErrorGeneracionRespuesta: {
            /** Fila */
            fila: number;
            /** Campo */
            campo: string;
            /** Detalle */
            detalle: string;
        };
        /**
         * EstadoCarga
         * @description Estado de procesamiento de una version (la ingesta corre en segundo plano).
         * @enum {string}
         */
        EstadoCarga: "en_cola" | "procesando" | "terminada" | "fallida";
        /**
         * FormatoArchivo
         * @description Formatos de archivo soportados (RF-13).
         * @enum {string}
         */
        FormatoArchivo: "xlsx" | "csv" | "json";
        /** FormatoFinancieroEntrada */
        FormatoFinancieroEntrada: {
            /**
             * Separador Miles
             * @default ,
             */
            separador_miles: string;
            /**
             * Separador Decimal
             * @default .
             */
            separador_decimal: string;
            /**
             * Decimales
             * @default 2
             */
            decimales: number;
        };
        /** FormatoRespuesta */
        FormatoRespuesta: {
            /** Formato */
            formato: string;
            /** Extension */
            extension: string;
            /** Opciones */
            opciones: string[];
        };
        /** GrupoRespuesta */
        GrupoRespuesta: {
            /** Valor */
            valor: unknown;
            /** Cuentas */
            cuentas: number;
            /** Capital */
            capital: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthRespuesta */
        HealthRespuesta: {
            /** Api */
            api: boolean;
            /** Database */
            database: boolean;
            /** Ok */
            ok: boolean;
        };
        /** IncidenciaRespuesta */
        IncidenciaRespuesta: {
            /** Fila */
            fila: number | null;
            /** Columna */
            columna: string | null;
            /** Codigo */
            codigo: string;
            severidad: components["schemas"]["Severidad"];
            /** Detalle */
            detalle: string;
            /** Valor Original */
            valor_original: string | null;
        };
        /** IncidenciasRespuesta */
        IncidenciasRespuesta: {
            /** Total */
            total: number;
            /** Incidencias */
            incidencias: components["schemas"]["IncidenciaRespuesta"][];
        };
        /** MetricasRespuesta */
        MetricasRespuesta: {
            /** Cuentas */
            cuentas: number;
            /** Capital Total */
            capital_total: string;
            /** Cuota Minima */
            cuota_minima: string | null;
            /** Cuota Maxima */
            cuota_maxima: string | null;
            /** Cuentas Por Segmento */
            cuentas_por_segmento: {
                [key: string]: number;
            };
            /** Adicionales */
            adicionales: {
                [key: string]: unknown;
            };
        };
        /** OpcionesEntrada */
        OpcionesEntrada: {
            /**
             * Delimitador
             * @default ,
             */
            delimitador: string;
            /**
             * Codificacion
             * @default utf-8
             */
            codificacion: string;
            /**
             * Con Cabeceras
             * @default true
             */
            con_cabeceras: boolean;
            /**
             * Hoja
             * @default Carga
             */
            hoja: string;
            /** Sangria */
            sangria?: number | null;
        };
        /** PaginaRespuesta */
        PaginaRespuesta: {
            /** Total */
            total: number;
            /** Limite */
            limite: number;
            /** Desplazamiento */
            desplazamiento: number;
            /** Suficiente */
            suficiente: boolean;
            /** Productos */
            productos: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ParteSeleccion
         * @enum {string}
         */
        ParteSeleccion: "nombre" | "filtro" | "orden" | "cantidad" | "indicador";
        /** PeticionGeneracion */
        PeticionGeneracion: {
            /**
             * Fecha Corte
             * Format: date
             */
            fecha_corte: string;
            definicion: components["schemas"]["DefinicionEntrada"];
            /** @default xlsx */
            formato: components["schemas"]["FormatoArchivo"];
            /**
             * Filtros
             * @default []
             */
            filtros: string[];
            /** Orden */
            orden?: string | null;
            /**
             * Cantidad
             * @default 1000
             */
            cantidad: number;
            opciones?: components["schemas"]["OpcionesEntrada"] | null;
        };
        /** PrevisualizacionRespuesta */
        PrevisualizacionRespuesta: {
            /** Nombre Archivo */
            nombre_archivo: string;
            /** Cabeceras */
            cabeceras: string[];
            /** Filas */
            filas: {
                [key: string]: unknown;
            }[];
            /** Disponibles */
            disponibles: number;
            /** Solicitados */
            solicitados: number;
            /** Generados */
            generados: number;
            /** Suficiente */
            suficiente: boolean;
            /** Completa */
            completa: boolean;
            /** Errores */
            errores: components["schemas"]["ErrorGeneracionRespuesta"][];
        };
        /** ProblemaRespuesta */
        ProblemaRespuesta: {
            parte: components["schemas"]["ParteSeleccion"];
            /** Expresion */
            expresion: string;
            /** Detalle */
            detalle: string;
        };
        /** ResumenRespuesta */
        ResumenRespuesta: {
            /** Disponibles */
            disponibles: number;
            /** Solicitados */
            solicitados: number | null;
            /** Suficiente */
            suficiente: boolean;
            universo: components["schemas"]["BloqueRespuesta"];
            seleccion: components["schemas"]["BloqueRespuesta"] | null;
        };
        /** RevisionRespuesta */
        RevisionRespuesta: {
            /** Aplicable */
            aplicable: boolean;
            /** Problemas */
            problemas: components["schemas"]["ProblemaRespuesta"][];
        };
        /** SegmentacionRespuesta */
        SegmentacionRespuesta: {
            /** Campo */
            campo: string;
            /** Grupos */
            grupos: components["schemas"]["GrupoRespuesta"][];
        };
        /** SeleccionEntrada */
        SeleccionEntrada: {
            /** Nombre */
            nombre: string;
            /**
             * Filtros
             * @default []
             */
            filtros: string[];
            /** Orden */
            orden?: string | null;
            /** Cantidad */
            cantidad?: number | null;
            /**
             * Indicadores
             * @default []
             */
            indicadores: string[];
        };
        /** SeleccionRespuesta */
        SeleccionRespuesta: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Filtros */
            filtros: string[];
            /** Orden */
            orden: string | null;
            /** Cantidad */
            cantidad: number | null;
            /** Indicadores */
            indicadores: string[];
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            /** Aplicable */
            aplicable: boolean;
            /** Problemas */
            problemas: components["schemas"]["ProblemaRespuesta"][];
        };
        /**
         * Severidad
         * @description Gravedad de una incidencia detectada al normalizar.
         * @enum {string}
         */
        Severidad: "error" | "advertencia" | "info";
        /**
         * TipoSalida
         * @description Tipado explicito de cada campo generado (RF-12).
         * @enum {string}
         */
        TipoSalida: "texto" | "numero" | "fecha" | "financiero";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionRespuesta */
        VersionRespuesta: {
            /** Id */
            id: number;
            /**
             * Fecha Corte
             * Format: date
             */
            fecha_corte: string;
            /** Version */
            version: number;
            estado: components["schemas"]["EstadoCarga"];
            /** Vigente */
            vigente: boolean;
            /** Nombre Archivo */
            nombre_archivo: string;
            /** Tamano Bytes */
            tamano_bytes: number;
            /** Hoja */
            hoja: string;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /** Procesado En */
            procesado_en: string | null;
            /** Huella Formato */
            huella_formato: string | null;
            /** Filas Total */
            filas_total: number | null;
            /** Filas Ingestadas */
            filas_ingestadas: number | null;
            /**
             * Incidencias Error
             * @default 0
             */
            incidencias_error: number;
            /**
             * Incidencias Advertencia
             * @default 0
             */
            incidencias_advertencia: number;
            /**
             * Incidencias Info
             * @default 0
             */
            incidencias_info: number;
            /** Motivo Fallo */
            motivo_fallo: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRespuesta"];
                };
            };
        };
    };
    listar_versiones_cargas_get: {
        parameters: {
            query?: {
                fecha_corte?: string | null;
                limite?: number;
                desplazamiento?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionRespuesta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subir_sabana_cargas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_subir_sabana_cargas_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargaCreadaRespuesta"];
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description El archivo supera el tamano maximo */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_version_cargas__carga_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carga_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionRespuesta"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_version_cargas__carga_id__delete: {
        parameters: {
            query?: {
                /** @description Confirma que la fecha quede sin version vigente (V-8) */
                dejar_fecha_sin_vigente?: boolean;
            };
            header?: never;
            path: {
                carga_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description La operacion choca con el estado actual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_incidencias_cargas__carga_id__incidencias_get: {
        parameters: {
            query?: {
                severidad?: components["schemas"]["Severidad"] | null;
                limite?: number;
                desplazamiento?: number;
            };
            header?: never;
            path: {
                carga_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenciasRespuesta"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asignar_vigente_cargas__carga_id__vigente_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carga_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionRespuesta"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description La operacion choca con el estado actual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_campos_cartera_campos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["CampoRespuesta"];
                    };
                };
            };
        };
    };
    consultar_cartera_cartera_get: {
        parameters: {
            query: {
                fecha_corte: string;
                filtro?: string[];
                /** @description campo, o -campo para descendente */
                orden?: string | null;
                limite?: number;
                desplazamiento?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaRespuesta"];
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metricas_cartera_cartera_metricas_get: {
        parameters: {
            query: {
                fecha_corte: string;
                filtro?: string[];
                indicador?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricasRespuesta"];
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segmentar_cartera_cartera_segmentacion_get: {
        parameters: {
            query: {
                fecha_corte: string;
                campo: string;
                filtro?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentacionRespuesta"];
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumir_cartera_cartera_resumen_get: {
        parameters: {
            query: {
                fecha_corte: string;
                filtro?: string[];
                /** @description Que productos son los primeros: campo, o -campo */
                orden?: string | null;
                /** @description El n del top n. Sin ella no hay bloque de seleccion */
                cantidad?: number | null;
                indicador?: string[];
                /** @description Campo por el que segmentar los dos bloques */
                segmento?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumenRespuesta"];
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_formatos_archivos_carga_formatos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormatoRespuesta"][];
                };
            };
        };
    };
    previsualizar_archivos_carga_previsualizacion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionGeneracion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrevisualizacionRespuesta"];
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generar_archivo_archivos_carga_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionGeneracion"];
            };
        };
        responses: {
            /** @description El archivo de carga en el formato pedido */
            200: {
                headers: {
                    /** @description attachment; filename="<nombre>.<extension>" */
                    "Content-Disposition"?: string;
                    /** @description Filas escritas en el archivo */
                    "X-Carga-Generados"?: string;
                    /** @description Productos que cumplen la seleccion completa */
                    "X-Carga-Disponibles"?: string;
                    /** @description Cantidad de productos pedida */
                    "X-Carga-Solicitados"?: string;
                    /** @description 1 si habia al menos tantos productos como se pidieron, 0 si no */
                    "X-Carga-Suficiente"?: "0" | "1";
                    /** @description Campos que no se pudieron generar; el detalle esta en /previsualizacion */
                    "X-Carga-Errores"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    "text/csv": string;
                    "application/json": string;
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_selecciones_selecciones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeleccionRespuesta"][];
                };
            };
        };
    };
    crear_seleccion_selecciones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeleccionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeleccionRespuesta"];
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description La operacion choca con el estado actual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisar_seleccion_selecciones_revision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeleccionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_seleccion_selecciones__seleccion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seleccion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeleccionRespuesta"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_seleccion_selecciones__seleccion_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seleccion_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeleccionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeleccionRespuesta"];
                };
            };
            /** @description La peticion no se puede atender tal como viene; el motivo esta en detail */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description La operacion choca con el estado actual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_seleccion_selecciones__seleccion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seleccion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe lo pedido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
